<?php

/**
 * @file
 * Provides primary Drupal hook implementations.
 *
 * Adds a JavaScript snippet to selected page responses to trigger analytics and
 * other tracking items configured using the Google Tag Manager.
 *
 * @author Jim Berry ("solotandem", http://drupal.org/user/240748)
 */

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Default for matching all items except listed.
 */
const GOOGLE_TAG_EXCLUDE_LISTED = 'exclude listed';

/**
 * Default for matching only listed items.
 */
const GOOGLE_TAG_INCLUDE_LISTED = 'include listed';

/**
 * Implements hook_help().
 */
function google_tag_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.google_tag':
    case 'google_tag.settings_form':
      return t('<a href=":url">Google Tag Manager</a> is a free service (registration required) to manage the insertion of tags for capturing website analytics.', array(':url' => 'https://tagmanager.google.com/'));
  }
}

/**
 * Implements hook_page_build().
 *
 * Adds the snippet to the page array if the insertion conditions are met.
 *
 * @see drupal_render_page()
 */
function google_tag_page_build(&$page) {
  if (!google_tag_insert_snippet()) {
    return;
  }

  // Call sequence:
  // - drupal_render_page()
  //   - hook_page_build()
  //   - hook_page_alter()
  //   - drupal_render()
  // - drupal_render()
  //   - callbacks in $elements['#theme_wrappers']
  //     - hook_preprocess_html(): 'html' is the wrapper for page
  //     - templates may add tags after body tag
  //   - callbacks in $elements['#post_render']
  //     - google_tag_page_process(): callback set here

  $wrapper = file_stream_wrapper_get_instance_by_uri('public://');

  // Add data_layer and script snippets to head (by default).
  $include_script_as_file = variable_get('google_tag_include_file', 1);
  if ($include_script_as_file) {
    $base_path = variable_get('file_public_path', conf_path() . '/files');
    foreach (['data_layer', 'script'] as $type) {
      $path = "$base_path/js/google_tag.$type.js";
      // @todo Will it matter if file is empty?
      drupal_add_js($path, array('group' => JS_LIBRARY * 2));
    }
  }
  else {
    $base_path = $wrapper->realpath();
    foreach (['data_layer', 'script'] as $type) {
      $url = "$base_path/js/google_tag.$type.js";
      $contents = file_get_contents($url);
      // @see drupal_get_js()
      // For inline JavaScript to validate as XHTML, all JavaScript containing
      // XHTML needs to be wrapped in CDATA.
      if ($contents) {
        drupal_add_js($contents, array('type' => 'inline', 'group' => JS_LIBRARY * 2));
      }
    }
  }

  // Add noscript snippet to page_top region.
  $base_path = $wrapper->realpath();
  $url = "$base_path/js/google_tag.noscript.js";
  $noscript = file_get_contents($url);

  // Note: for any theme that follows the pattern of core html.tpl.php in the
  // system module (e.g. bootstrap theme), this does not place the snippet
  // immediately after the body tag but rather after the 'skip-link' div.
  $page['page_top']['google_tag'] = array(
    '#markup' => $noscript,
    '#weight' => -10,
  );
}

/**
 * Determines whether to insert the snippet on the response.
 *
 * @return boolean
 *   TRUE if the conditions are met; FALSE otherwise.
 */
function google_tag_insert_snippet() {
  static $satisfied;

  if (!isset($satisfied)) {
    $config = \Drupal::config('google_tag.settings');
    $id = $config->get('container_id');

    if (empty($id)) {
      // No container ID.
      return FALSE;
    }

    $satisfied = TRUE;
    if (!_google_tag_status_check() || !_google_tag_path_check() || !_google_tag_role_check()) {
      // Omit snippet if any condition is not met.
      $satisfied = FALSE;
    }

    // Allow other modules to alter the insertion criteria.
    \Drupal::moduleHandler()->alter('google_tag_insert', $satisfied);
  }
  return $satisfied;
}

/**
 * Determines whether to insert the snippet based on status code settings.
 *
 * @return boolean
 *   TRUE if the status conditions are met; FALSE otherwise.
 */
function _google_tag_status_check() {
  // @todo Response object does not exist at this point; the response status
  //   code can not be had from it. Does the routing object include equivalent
  //   property? Defer.
  return TRUE;
  static $satisfied;

  if (!isset($satisfied)) {
    $config = \Drupal::config('google_tag.settings');
    $toggle = $config->get('status_toggle');
    $statuses = $config->get('status_list');

    if (empty($statuses)) {
      $satisfied = ($toggle == GOOGLE_TAG_EXCLUDE_LISTED);
    }
    else {
      // Get the HTTP response status.
      $response = \Drupal::service('response');
      $status = $response->getStatusCode();
      $satisfied = strpos($statuses, (string) $status) !== FALSE;
      $satisfied = ($toggle == GOOGLE_TAG_EXCLUDE_LISTED) ? !$satisfied : $satisfied;
    }
  }
  return $satisfied;
}

/**
 * Determines whether to insert the snippet based on the path settings.
 *
 * @return boolean
 *   TRUE if the path conditions are met; FALSE otherwise.
 */
function _google_tag_path_check() {
  static $satisfied;

  if (!isset($satisfied)) {
    $config = \Drupal::config('google_tag.settings');
    $toggle = $config->get('path_toggle');
    $paths = Unicode::strtolower($config->get('path_list'));

    if (empty($paths)) {
      $satisfied = ($toggle == GOOGLE_TAG_EXCLUDE_LISTED);
    }
    else {
      $request = \Drupal::request();
      $current_path = \Drupal::service('path.current');
      $alias_manager = \Drupal::service('path.alias_manager');
      $path_matcher = \Drupal::service('path.matcher');
      // @todo Are not some paths case sensitive???
      // Compare the lowercase path alias (if any) and internal path.
      $path = rtrim($current_path->getPath($request), '/');
      $path_alias = Unicode::strtolower($alias_manager->getAliasByPath($path));
      $satisfied = $path_matcher->matchPath($path_alias, $paths) || (($path != $path_alias) && $path_matcher->matchPath($path, $paths));
      $satisfied = ($toggle == GOOGLE_TAG_EXCLUDE_LISTED) ? !$satisfied : $satisfied;
    }
  }
  return $satisfied;
}

/**
 * Determines whether to insert the snippet based on the user role settings.
 *
 * @return boolean
 *   TRUE if the role conditions are met; FALSE otherwise.
 */
function _google_tag_role_check() {
  static $satisfied;

  if (!isset($satisfied)) {
    $config = \Drupal::config('google_tag.settings');
    $toggle = $config->get('role_toggle');
    $roles = $config->get('role_list');
    $roles = array_filter($roles);

    if (empty($roles)) {
      $satisfied = ($toggle == GOOGLE_TAG_EXCLUDE_LISTED);
    }
    else {
      $satisfied = FALSE;
      // Check user roles against listed roles.
      $satisfied = (boolean) array_intersect($roles, \Drupal::currentUser()->getRoles());
      $satisfied = ($toggle == GOOGLE_TAG_EXCLUDE_LISTED) ? !$satisfied : $satisfied;
    }
  }
  return $satisfied;
}
